
INSERT INTO customers (first_name, last_name, company) VALUES
    ('John', 'Doe', 'Acme Corp'),
    ('John', 'Smith', 'Acme Corp'),
    ('John', 'Johnson', 'Wayne Enterprises'),
    ('Smith', 'John', 'Stark Industries'),
    ('Michael', 'Smith', 'Oscorp'),
    ('Olivia', 'Smith', 'Acme Corp'),
    ('Daniel', 'Smith', 'Acme Corp'),
    ('Sophia', 'Taylor', 'Umbrella Corporation'),
    ('William', 'Martinez', 'Weyland-Yutani Corp'),
    ('Ava', 'Thomas', 'Tyrell Corporation'),
    ('James', 'Hernandez', 'Acme Corp'),
    ('Isabella', 'Moore', 'Buy n Large'),
    ('Benjamin', 'Martin', 'Acme Corp'),
    ('Mia', 'Jackson', 'Soylent Green'),
    ('Joseph', 'White', 'Acme Corp'),
    ('Charlotte', 'Harris', 'Virtucon'),
    ('David', 'Garcia', 'Acme Corp'),
    ('Amelia', 'Clark', 'Cyberdyne Systems'),
    ('Henry', 'Lewis', 'Stark Industries'),
    ('Harper', 'Lee', 'Stark Industries');
